---
- name: removing httpd server packages
  hosts: all
  become: true
#  gather_facts: no

  tasks:
  - name: removing httpd packages
    yum: 
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat" 

  - name: removing apache2 packages
    apt:
      name: apache2
      state: absent 
    when: ansible_os_family == "Debian"
